-- =====================================================
-- Migration V15: Add GS1 Help System / Education System
-- Created: December 14, 2025
-- Purpose: Support in-app GS1 education with contextual help
-- =====================================================

-- Create GS1 help content table
CREATE TABLE IF NOT EXISTS gs1_help_content (
  id SERIAL PRIMARY KEY,
  topic_key VARCHAR(100) UNIQUE NOT NULL, -- e.g., 'gtin', 'sscc', 'gln'
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50), -- 'identifiers', 'workflows', 'concepts'
  related_topics TEXT[], -- Array of related topic keys
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_gs1_help_topic_key ON gs1_help_content(topic_key);
CREATE INDEX idx_gs1_help_category ON gs1_help_content(category);

-- Pre-populate with GS1 concepts from Tatmeen analysis
INSERT INTO gs1_help_content (topic_key, title, description, category, related_topics) VALUES
(
  'gtin',
  'GTIN - Global Trade Item Number',
  'GTIN = (01)GTIN. The **Global Trade Item Number (GTIN)** is the globally unique 14-digit identification key used to identify trade items (any product that may be priced at any point in the supply chain). GTINs are assigned by the brand owner of the product and are used to identify products as they move through the global supply chain. In order to automate the reading process, the GTIN is often encoded in a barcode. Example: (01)03868836000154',
  'identifiers',
  ARRAY['sgtin', 'batch_lot']
),
(
  'sscc',
  'SSCC - Serial Shipping Container Code',
  'The **Serial Shipping Container Code (SSCC)** is a unique 18-digit number used to identify a logistic unit (e.g., a pallet, case, or package). The SSCC is generated by the entity that creates the logistic unit and is used to track the unit throughout the supply chain. The SSCC comprises a GS1 Company Prefix, Serial Reference, and Check Digit. Format: (00)123456789012345678',
  'identifiers',
  ARRAY['gln', 'hierarchy']
),
(
  'sgtin',
  'SGTIN - Serialized GTIN',
  'The **Serialized Global Trade Item Number (SGTIN)** is used for unique unit-level identification. It combines the GTIN with a unique serial number to identify individual items. Format: urn:epc:id:sgtin:CompanyPrefix.ItemRef.SerialNumber',
  'identifiers',
  ARRAY['gtin', 'commissioning']
),
(
  'gln',
  'GLN - Global Location Number',
  'The **Global Location Number (GLN)** is GS1 13-digit Identification Key and it is used to uniquely identify physical locations or legal entities. The location identified with GLN could be a physical location such as a warehouse or a legal entity such as a company or customer. The GLN is used in electronic messaging between customers and suppliers, where location advice is important. The GLN comprises a GS1 Company Prefix, Location Reference, and Check Digit. In order to automate the reading process, the GLN is often encoded in a barcode.',
  'identifiers',
  ARRAY['manufacturer_gln', 'destination_gln']
),
(
  'batch_lot',
  'Batch/Lot Number',
  'Batch/Lot = (10)Batch/Lot. A batch number or lot is a designation given to products made in the same manufacturing run. A batch number can consist of numerals, letters, or symbols, and it allows the items to be tracked after they''ve been distributed. Example: (10)Lot655',
  'concepts',
  ARRAY['gtin', 'manufacturing_date']
),
(
  'manufacturing_date',
  'Manufacturing Date',
  'MANUFACTURING DATE = (11)MANUFACTURING DATE (YYMMDD). The **manufacturing or production date** is the date when the batch (or lot) was produced. The manufacturing date is usually written in the format YYMMDD. Example: (11)220630 represents June 30, 2022',
  'concepts',
  ARRAY['batch_lot', 'manufacturing_origin']
),
(
  'manufacturing_origin',
  'Manufacturing Origin',
  'Manufacturing origin tells where the items were made. You can select: • **Import**, if items were produced outside Kenya • **Domestic production**, if items were made in Kenya. This helps regulatory authorities track the source of pharmaceutical products.',
  'concepts',
  ARRAY['manufacturing_date', 'manufacturer_gln']
),
(
  'manufacturer_gln',
  'Manufacturer GLN',
  'The **Manufacturer Global Location Number (GLN)** is GS1 13-digit Identification Key used to uniquely identify physical locations or legal entities. In the case of manufacturing, GLN represents the manufacturing location where items were made. The GLN is used in electronic messaging between customers and suppliers. The GLN comprises a GS1 Company Prefix, Location Reference, and Check Digit.',
  'identifiers',
  ARRAY['gln', 'manufacturing_origin']
),
(
  'reference_document',
  'Reference Document Number',
  'The **reference document number** is used as a search criterion when displaying or changing documents. It could be a Purchase Order number, Invoice number, or other external document reference. In correspondence, the reference document number is sometimes printed in place of the internal document number.',
  'workflows',
  ARRAY['returns', 'shipments']
),
(
  'destination_gln',
  'Destination GLN',
  'The **Destination GLN** represents the location where shipping items will be delivered. It uses the GS1 Global Location Number (GLN) standard to uniquely identify the destination. This is required for shipments to ensure proper delivery tracking.',
  'identifiers',
  ARRAY['gln', 'shipments']
),
(
  'commissioning',
  'Product Commissioning',
  'Product commissioning is the process of assigning unique identifiers (SGTINs) to individual product units during manufacturing. This enables unit-level tracking throughout the supply chain. Mobile commissioning allows this to be done using a mobile device at the manufacturing site.',
  'workflows',
  ARRAY['sgtin', 'mobile_commissioning', 'manufacturing_date']
),
(
  'hierarchy',
  'Hierarchy Management (Pack/Unpack)',
  'Hierarchy management involves organizing products into cases, and cases into packages/pallets. **Pack** operations create aggregations (adding items to a container), while **Unpack** operations break down aggregations (removing items from a container). Each operation generates a new SSCC and is tracked via EPCIS events.',
  'workflows',
  ARRAY['sscc', 'pack_operation', 'unpack_operation']
),
(
  'returns',
  'Return Logistics',
  'Return logistics handles the reverse flow of products back through the supply chain. **Return Receiving** is when you accept returned products from customers or facilities. **Return Shipping** is when you send products back to manufacturers or suppliers. All returns must be tracked with reference document numbers and quality checks.',
  'workflows',
  ARRAY['reference_document', 'quality_check']
),
(
  'destruction',
  'Product Destruction',
  'Product destruction is the controlled disposal of pharmaceutical products that are expired, damaged, recalled, or quarantined. The process has two phases: **Initiation** (requesting destruction) and **Completion** (executing and documenting destruction). Large quantities require manager approval.',
  'workflows',
  ARRAY['destruction_initiation', 'destruction_completion']
);

-- Comments for documentation
COMMENT ON TABLE gs1_help_content IS 'GS1 education system - contextual help content for GS1 concepts';
COMMENT ON COLUMN gs1_help_content.topic_key IS 'Unique key for the help topic (used in HelpIcon component)';
COMMENT ON COLUMN gs1_help_content.related_topics IS 'Array of related topic keys for cross-referencing';
